# NumPy 簡介

### Numpy 是 Numerical Python 的簡稱，是 Python 用來作科學運算的基礎套件。

#### 這一份筆記主要說明以下重點：

* 為何需要 Numpy？
* Numpy 比 pure python 提供了那些不一樣的東西？
* 怎麼使用 Numpy 的 ndarray？
* 投資理財相關領域中常用的 Numpy 的函式有哪些？

#### 參考資料：

* [Numpy 官網](http://www.numpy.org/)
* [Numpy 教學](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [Python Numpy Array Tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutoria)

## 為什麼需要 Numpy?

### 關於向量運算：

在工程、科學及金融領域，需要用到很多向量運算。簡單說明如下：

假設有兩個向量 (Vectors) A 跟 B，

$A = \left(
    \begin{array}{c}
      a_1 \\
      a_2 \\
      a_3
    \end{array}
  \right)
$

$B = \left(
    \begin{array}{c}
      b_1 \\
      b_2 \\
      b_3
    \end{array}
  \right)
$

向量加法運算如下：

$A + B = \left(
    \begin{array}{c}
      a_1 + b_1 \\
      a_2 + b_2 \\
      a_3 + b_3
    \end{array}
  \right)
$

向量的純量積算法如下：

$c \cdot A = 
  \left(
    \begin{array}{c}
      ca_1 \\
      ca_2 \\
      ca_3
    \end{array}
  \right)
$

### 1. python 的 list 沒有辦法直接作向量運算。

In [1]:
A = [1, 2, 3]
B = [4, 5, 6]
A + B

[1, 2, 3, 4, 5, 6]

In [2]:
A * 2

[1, 2, 3, 1, 2, 3]

### 2. 替代性的方法運算速度緩慢

In [ ]:
list(zip(A, B))

In [3]:
C = []
for i, j in zip(A, B):
    C.append(i + j)
C

[5, 7, 9]

In [4]:
D = []
for i in A:
    D.append(i * 2)
D

[2, 4, 6]

### 3. Numpy 提供簡易即迅速的方式執行上面那些向量運算

In [5]:
import numpy as np

In [6]:
A1 = np.array(A)
B1 = np.array(B)
A1 + B1

array([5, 7, 9])

In [7]:
A1 * 2

array([2, 4, 6])

In [ ]:
A1.dtype

## Numpy 提供了什麼不一樣的東西？

#### Numpy 中主要提供了一個叫做多維陣列 ndarray, or N-dimensional Array 的資料結構，透過它可以直接作向量運算。
#### ndarray 提供一些重要的屬性，如 dtype 及 shape等，dtype 為 ndarry 裡面的資料的型態，而 shape 則為資料的形狀。
#### 底下會用例子加以說明。

### Numpy 中的兩大概念：

* 資料結構
  - ndarray
    - dtype
    - shape
    - ndim
    - size


* 通用函式
  - ufunc
  

### 如何創建 ndarray？

### 最簡單的方法就是使用 Numpy 的 array 函式。

In [ ]:
X = [1, 2, 3]
Y = np.array(X)
Y

In [ ]:
X

In [ ]:
Z = np.array([4, 5, 6])
Z

In [ ]:
Z.dtype

In [ ]:
Z.shape

### 其他的創建方式

|函式|說明|
|:-|:-|
|array|將輸入的資料轉換成 ndarray。|
|arange|range 的 ndarray 版。|
|linspace|返回平均分配特定區間的數值。|
|logspace|返回平均分配在 log scale 上的數值。|
|ones, ones_like|創建一個全部是1的ndarray。|
|zeros, zeros_like|創建一個全部是0的ndarray。|
|empty, empty_like|創建一個未填入資料的ndarray。|
|eye, identity|創建一個單位矩陣。|

In [8]:
N = 10
x1 = np.linspace(0.1, 1, N, endpoint=True)
x2 = np.linspace(0.1, 1, N, endpoint=False)

In [9]:
x1

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
x2

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

In [11]:
x1.shape

(10,)

In [12]:
x2.shape

(10,)

In [13]:
N = 10
x1 = np.logspace(0.1, 1, N, endpoint=True)
x2 = np.logspace(0.1, 1, N, endpoint=False)

In [14]:
x1

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [15]:
x2

array([1.25892541, 1.54881662, 1.90546072, 2.34422882, 2.8840315 ,
       3.54813389, 4.36515832, 5.37031796, 6.60693448, 8.12830516])

In [ ]:
I = np.eye(4)
I

In [ ]:
I.shape

In [16]:
G = np.arange(25)
G

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
G.shape

(25,)

In [18]:
F = G.reshape(5, 5)
F

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
G

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
G.shape = 5, 5
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G.shape

### ndarray 的 indexing

In [21]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
G[1, 1]

6

In [23]:
G[1]

array([5, 6, 7, 8, 9])

In [24]:
G[1][1]

6

### ndarray 的 slicing

In [25]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
G[0]

array([0, 1, 2, 3, 4])

In [27]:
G[0, :]

array([0, 1, 2, 3, 4])

In [28]:
G[:, 0]

array([ 0,  5, 10, 15, 20])

In [29]:
G[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
G

### ndarray 的 boolean indexing

In [30]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
G > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [32]:
G[G > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
np.where(G > 10, G, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.all(G > -1)

In [ ]:
np.all(G < 25)

In [ ]:
np.all(G > 0)

In [ ]:
G

In [ ]:
np.any(G > 0)

### 什麼是 ufunc？

* universal function 的縮寫
* 用來對 ndarray 裡面的每個元素作操作的函式。
* ufunc 可以被看作是一般 python 函式的向量化版本。
* Numpy 的 ufunc 都是衍生自 numpy.ufunc 類別。
* 很多內建的 ufunc 底層都是使用 C 實作的，所以速度很快。

詳細內容請參考：[ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [ ]:
isinstance(np.sin, np.ufunc)

In [ ]:
isinstance(np.arange, np.ufunc)

In [ ]:
import math
math.pi

In [ ]:
K = np.arange(0, 2, 0.1)
K = K * math.pi
K

In [ ]:
np.sin(K)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(np.sin(K))

### numpy 有哪些 ufuncs？

想知道 numpy 有哪些 ufunc ，可以參考官網上面的連結：[Available ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)

## 金融投資相關領域中常用的 numpy 函式有哪些？

* [Numpy 的函式列表](https://docs.scipy.org/doc/numpy/reference/routines.html)

### 統計相關函式

參考：[Statistics](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.statistics.html)

|函式|說明|
|:-|:-|
|sum|總和|
|mean|平均|
|std|標準差|
|var|變異數|
|min, max|最小值、最大值|
|argmin, argmax|最小值的索引、最大值的索引|
|cumsum|和的累計值|
|cumprod|積的累計值|

### 亂數相關函式

參考：[Random Sampling (numpy.random)](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

|函式|說明|
|:-|:-|
|[seed](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html#numpy.random.seed)|設定亂數的種子|
|[permutation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.permutation.html)|隨機排列|
|[shuffle](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.shuffle.html)|沿著 axis 0 的隨機排列|
|[rand](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand)|返回指定形狀的亂數，亂數值為[0,1]間的均勻分布|
|[randn](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html#numpy.random.randn)|返回指定形狀的亂數，亂數值為mean為0，variance為1的高斯分布|
|[randint](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html#numpy.random.randint)|使用離散均勻分布，返回指定形狀的整數亂數|
|[normal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html#numpy.random.normal)|返回指定形狀的亂數，亂數值為自訂的mean跟variance的高斯分布|
|[uniform](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html#numpy.random.uniform)|使用均勻分布，返回指定形狀的亂數|

In [ ]:
np.random.rand(5)